# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 694a1b8ac1a370f298932a4b69dcdefbc11080f5c61b6a2061d203a1aa6fcc287939d891d9591dde1a14b982a2598f1b2b5f7feb3ef04d446f2d760961e6e981

test:
  secret_key_base: 098dfe5fe0cb6f95989056341f79f6ff0b483e4e105f399babfc526975169c56c76b3ce14d73584bdff02ce57292536d3cfc6683502532c95c9660b6de185e50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
